services:
  bottifront:
    image: bonda23/autotecnicabottifront:v0.0.10
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5173:5173